# Site settings
title: David Ayeke
email: ayekedavid@yahoo.com
url: http://ayeke.me
description: "David Ayeke's protfolio site"
skills: "Web Developer - Software Engineer - Computer Engineer"
meta_author: David Ayeke

google-analytics: UA-73360105-1

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 022D7224AE85E7DEFC50933BD4753FF0

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: David Ayeke
  location: St. Louis
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/david.ayeke
  - title: github
    url: http://github.com/Dacode45

# Postal address (add as many lines as necessary)
address:
  - line: 6410 Cates Ave, Apt 1W
  - line: St. Louis, MO 63130

# Credits content
credits: Built using the <a href="https://github.com/jeromelachaud/freelancer-theme">freelancer</a> theme

# Build settings
markdown: kramdown
permalink: pretty
